<div style="direction:rtl;line-height:300%;"><font face="XB Zar" size=5>
<div align=center>
   <br>
    <font face="Times New Roman" size=18>
    <p></p>
    In the name of God  
    </font>
    <br><br>
    <font face="Times New Roman" size=5 color=blue>
    Python for Data Mining<br>      </font>
    <font face="Times New Roman" size=4 color=blue> 
        Insurance Research Center
    </font>
    <br>
    <br>
    <font face="Times New Roman" size=4 color=#FF7500>
    Khayyam Salehi 
    </font>
    <br>       
    <font face="Times New Roman" size=3 color=#FF7500>
    Assistant Professor
    <br>
    Department of Computer science
    <br>
    Shahrekord University
    </font>
    <br>    <br>
</div>

<hr style="border:2px solid black"> </hr>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Regression

* Regularization with SciKit-Learn
    * Ridge Regression
    * Lasso Regression
    * Elastic Net

## Regularization with SciKit-Learn

* minimizing te model complexity
* adding penalty to loss function (thus reducing the overfitting)

Three types of regularization methods:
1. L1 regularization (Lasso regression)
$$\frac{1}{2n}\sum_{i = 1}^n \Big(y_i - \sum_{j = 0}^m \beta_j x_{ij}\Big)^2 + \lambda \sum_{j = 1}^m |\beta_j| $$
2. L2 regularization (Ridge regression)
$$\frac{1}{2n}\sum_{i = 1}^n \Big(y_i - \sum_{j = 0}^m \beta_j x_{ij}\Big)^2 + \lambda \sum_{j = 1}^m \beta_j^2 $$
3. Mixing L1 and L2 (Elastic nets)
$$\frac{1}{2n}\sum_{i = 1}^n \Big(y_i - \sum_{j = 0}^m \beta_j x_{ij}\Big)^2 + \lambda\Big( \frac{1-\alpha}{2}\sum_{j = 1}^m \beta_j^2 + \alpha \sum_{j = 1}^m |\beta_j|\Big)$$

# Framework:
1. Pre-processing step

`from sklearn.preprocessing import PolynomialFeatures`

2. Splitting into train and test sets:

`from sklearn.model_selection import train_test_split`<br>
`X_train, X_test, y_train, y_test = train_test_split(X, y)`

3. Scaling data

`from sklearn.preprocessing import StandardScaler`<br>
`scaler = StandardScaler()`<br>
`scaler.fit(X_train)`<br>
`X_train = scaler.transform(X_train)`<br>
`X_test = scaler.transform(X_test)`<br>


4. Importing model algorithms:

`from sklearn.model_family import ModelAlgorithm`<br>

5. Creating an instance of the model:

`mymodel = ModelAlgorithm(param_1, param_2, ...)`

6. Training the model:

`mymodel.fit(X_train, y_train)`

7. Predicting the $\hat{y}$:

`predictions = mymodel.predict(X_test)`

8. Importing error metrics

`from sklearn.metrics import error_metric`

9. Comparing with y_test:

`performance = error_metric(y_test, predictions)`

### Data

In [2]:
df = pd.read_csv("./data/Advertising.csv")
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
df.drop("Unnamed: 0", axis = 1, inplace=True)
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('sales',axis=1)
y = df['sales']
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

### Preprocessing step (Polynomial conversion)

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
# help(PolynomialFeatures)

In [14]:
poly_conv = PolynomialFeatures(degree=3, include_bias=True)

In [15]:
poly_features = poly_conv.fit_transform(X)

In [16]:
poly_features.shape

(200, 20)

### Splitting into Train & Test sets

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=32)

In [20]:
X_train

array([[1.00000000e+00, 2.18400000e+02, 2.77000000e+01, ...,
        4.09732860e+04, 7.89882120e+04, 1.52273304e+05],
       [1.00000000e+00, 6.61000000e+01, 5.80000000e+00, ...,
        8.14088000e+02, 3.39671200e+03, 1.41724880e+04],
       [1.00000000e+00, 2.20300000e+02, 4.90000000e+01, ...,
        7.68320000e+03, 5.01760000e+02, 3.27680000e+01],
       ...,
       [1.00000000e+00, 2.62700000e+02, 2.88000000e+01, ...,
        1.31880960e+04, 7.28092800e+03, 4.01967900e+03],
       [1.00000000e+00, 2.19800000e+02, 3.35000000e+01, ...,
        5.06134750e+04, 6.81393350e+04, 9.17338510e+04],
       [1.00000000e+00, 2.06900000e+02, 8.40000000e+00, ...,
        1.86278400e+03, 5.85446400e+03, 1.83997440e+04]])

In [21]:
y_train

20     18.0
10      8.6
128    24.7
40     16.6
5       7.2
       ... 
190    10.8
124    19.7
54     20.2
133    19.6
43     12.9
Name: sales, Length: 140, dtype: float64

In [22]:
X_test.shape

(60, 20)

In [23]:
y_test

122    11.6
186    10.3
167    12.2
101    23.8
29     10.5
75      8.7
144    11.4
28     18.9
121     7.0
182     8.7
27     15.9
181    12.2
39     21.5
23     15.5
2       9.3
173    11.7
107     8.7
17     24.4
109    19.8
118    15.9
26     15.0
46     10.6
21     12.5
160    14.4
44      8.5
143    10.4
56      5.5
188    15.9
79     11.0
73     11.0
164    11.9
18     11.3
102    14.8
131    12.7
96     11.7
141    19.2
115    12.6
174    11.5
130     1.6
34      9.5
156    15.3
154    15.6
153    19.0
197    12.8
185    22.6
113    15.9
33     17.4
169    15.0
183    26.2
14     19.0
136     9.5
22      5.6
86     12.0
145    10.3
168    17.1
85     15.2
117     9.4
57     13.2
31     11.9
97     15.5
Name: sales, dtype: float64

### Scaling the Data
* resulting faster convergence steepest descent algorithms
* avoiding updating some weights faster than others
* permitting comparison of coefficients

* Two types of scalling data
    * standardization $\Big($$\frac{X-\mu}{\sigma}$, thus $\mu_{rescale} = 0$ and $\sigma_{rescale} = 1$.$\Big)$
    * normalization $\Big($$\frac{X-X_{min}}{X_{max}-X_{min}}$. All values are between 0 and 1.$\Big)$

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler = StandardScaler()

In [26]:
scaler.fit(X_train)

StandardScaler()

In [27]:
X_train = scaler.transform(X_train)
X_train

array([[ 0.        ,  0.87449262,  0.19977365, ...,  0.26373599,
         0.56806103,  0.48153193],
       [ 0.        , -0.90408837, -1.2592688 , ..., -0.73106054,
        -0.57343542, -0.39278666],
       [ 0.        ,  0.89668109,  1.61884234, ..., -0.56090353,
        -0.61715168, -0.48230547],
       ...,
       [ 0.        ,  1.39183431,  0.27305889, ..., -0.42453997,
        -0.51478043, -0.45706427],
       [ 0.        ,  0.89084202,  0.58618672, ...,  0.50253624,
         0.40423368,  0.09825563],
       [ 0.        ,  0.74019399, -1.08604914, ..., -0.70508295,
        -0.53632126, -0.36602384]])

In [28]:
X_test = scaler.transform(X_test)

### Ridge Regression
#### Import a model class from a model family

In [29]:
from sklearn.linear_model import Ridge

#### Create an instance of the model with parameters

In [30]:
help(Ridge)

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(alpha=1.0, *, fit_intercept=True, normalize=False, copy_X=True, max_iter=None, tol=0.001, solver='auto', random_state=None)
 |  
 |  Linear least squares with l2 regularization.
 |  
 |  Minimizes the objective function::
 |  
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |  
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Regularization strength; must be a positive float. Regul

In [52]:
ridge_model = Ridge(alpha=1)

#### Fit or train the model on the training data

**Only fit to the training data**

In [53]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=1)

#### Evaluation on the test set

In [54]:
test_predictions = ridge_model.predict(X_test)
test_predictions

array([11.91472377, 10.37386068, 12.33076545, 23.46590763, 10.1318619 ,
        8.31893052, 11.09877464, 19.08151337,  7.90263212,  8.25815093,
       15.83955465, 12.48316072, 21.50645637, 15.64531275,  8.56079495,
       11.98426979,  8.74396977, 24.10444062, 19.3276398 , 16.35395821,
       15.40101319, 10.13050408, 12.62776251, 14.45559837,  8.47293213,
       10.04712612,  7.40252249, 15.96480468, 10.61889589, 10.76554146,
       11.6236719 , 10.33181472, 14.3586292 , 11.78867619, 11.89337287,
       19.68365363, 12.58990258, 12.1720459 ,  7.42560219,  8.93510155,
       14.89656372, 15.56925792, 19.23835736, 12.65770696, 22.43859811,
       16.16855961, 17.56087425, 14.86930797, 25.5643202 , 19.2351399 ,
        9.28350318,  7.2607475 , 11.53410942, 10.30777792, 17.23394753,
       15.39413184,  8.28826695, 13.24109811, 12.17957098, 15.47468327])

In [55]:
ridge_model.coef_

array([ 0.00000000e+00,  3.54944376e+00,  8.52991149e-01,  2.41395515e-01,
       -1.01992806e+00,  2.56820681e+00, -4.54739518e-02, -1.10250472e-02,
        4.64491589e-02, -2.36702808e-03, -5.08756237e-01,  1.16182771e-01,
       -6.51446098e-01,  5.58850601e-01,  5.72342291e-01,  1.72296241e-01,
       -2.51877494e-03, -4.23534766e-01, -7.27773612e-02,  9.24921891e-03])

#### Measuring the performance

In [56]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [57]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [58]:
MAE

0.45203391132118753

In [59]:
MSE

0.8250422902548593

In [60]:
RMSE

0.9083183859500255

In [ ]:
#Linear Regression
MAE: 1.3654567890610607
MSE: 3.7495203698290354
RMSE: 1.936367829165997

In [ ]:
#Polynomial Regression with degree=3
MAE: 0.4398382787964448
MSE: 0.6539211723519339
RMSE: 0.8086539261958319

In [ ]:
#Ridge Regression with alpha=10
MAE: 0.5432166936174314
MSE: 1.2072691637857988
RMSE: 1.098758009657176

In [ ]:
#Ridge Regression with alpha=1
MAE: 0.45203391132118753
MSE: 0.8250422902548593
RMSE: 0.9083183859500255

In [ ]:
#Ridge Regression with alpha=0.1
MAE: 0.37667327450782523
MSE: 0.5909221607140983
RMSE: 0.7687146159102859

### Choosing an alpha value with Cross-Validation

In [61]:
from sklearn.linear_model import RidgeCV

In [62]:
help(RidgeCV)

Help on class RidgeCV in module sklearn.linear_model._ridge:

class RidgeCV(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidgeCV)
 |  RidgeCV(alphas=(0.1, 1.0, 10.0), *, fit_intercept=True, normalize=False, scoring=None, cv=None, gcv_mode=None, store_cv_values=False, alpha_per_target=False)
 |  
 |  Ridge regression with built-in cross-validation.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  By default, it performs efficient Leave-One-Out Cross-Validation.
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alphas : ndarray of shape (n_alphas,), default=(0.1, 1.0, 10.0)
 |      Array of alpha values to try.
 |      Regularization strength; must be a positive float. Regularization
 |      improves the conditioning of the problem and reduces the variance of
 |      the estimates. Larger values specify stronger regularization.
 |      Alpha corresponds to ``1 / (2C)`` in other linear mod

In [64]:
from sklearn.metrics import SCORERS
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [68]:
# Choosing a scoring: https://scikit-learn.org/stable/modules/model_evaluation.html
# The 'higher is better' principle

ridge_cv_model = RidgeCV(alphas=(0.01, 0.1, 0.5, 1.0, 5, 10.0),scoring='neg_root_mean_squared_error')

In [69]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.01,  0.1 ,  0.5 ,  1.  ,  5.  , 10.  ]),
        scoring='neg_root_mean_squared_error')

In [70]:
ridge_cv_model.alpha_

0.01

In [71]:
test_predictions = ridge_cv_model.predict(X_test)

In [72]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [73]:
MAE

0.37605916788444943

In [74]:
RMSE

0.7145278827356524

In [75]:
ridge_cv_model.coef_

array([ 0.        ,  7.16372876,  1.03929253,  0.73801844, -9.17880659,
        3.97370905, -1.53292423, -0.70954368, -0.7325189 ,  0.21409593,
        4.08051569, -0.57156972,  0.58065798,  0.01156778,  0.58698809,
        0.21109142,  0.48680158, -0.03146252,  0.05596441, -0.18579086])

In [76]:
ridge_cv_model.best_score_

-0.4703239390917082

## Lasso Regression

* The higher $\lambda$ forces the coefficients equal to zero

In [63]:
from sklearn.linear_model import Lasso
help(Lasso)

Help on class Lasso in module sklearn.linear_model._coordinate_descent:

class Lasso(ElasticNet)
 |  Lasso(alpha=1.0, *, fit_intercept=True, normalize=False, precompute=False, copy_X=True, max_iter=1000, tol=0.0001, warm_start=False, positive=False, random_state=None, selection='cyclic')
 |  
 |  Linear Model trained with L1 prior as regularizer (aka the Lasso)
 |  
 |  The optimization objective for Lasso is::
 |  
 |      (1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
 |  
 |  Technically the Lasso model is optimizing the same objective function as
 |  the Elastic Net with ``l1_ratio=1.0`` (no L2 penalty).
 |  
 |  Read more in the :ref:`User Guide <lasso>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : float, default=1.0
 |      Constant that multiplies the L1 term. Defaults to 1.0.
 |      ``alpha = 0`` is equivalent to an ordinary least square, solved
 |      by the :class:`LinearRegression` object. For numerical
 |      reasons, using ``alpha = 0`` with the ``Lasso`` o

In [77]:
from sklearn.linear_model import LassoCV
help(LassoCV)

Help on class LassoCV in module sklearn.linear_model._coordinate_descent:

class LassoCV(sklearn.base.RegressorMixin, LinearModelCV)
 |  LassoCV(*, eps=0.001, n_alphas=100, alphas=None, fit_intercept=True, normalize=False, precompute='auto', max_iter=1000, tol=0.0001, copy_X=True, cv=None, verbose=False, n_jobs=None, positive=False, random_state=None, selection='cyclic')
 |  
 |  Lasso linear model with iterative fitting along a regularization path.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  The best model is selected by cross-validation.
 |  
 |  The optimization objective for Lasso is::
 |  
 |      (1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
 |  
 |  Read more in the :ref:`User Guide <lasso>`.
 |  
 |  Parameters
 |  ----------
 |  eps : float, default=1e-3
 |      Length of the path. ``eps=1e-3`` means that
 |      ``alpha_min / alpha_max = 1e-3``.
 |  
 |  n_alphas : int, default=100
 |      Number of alphas along the regularization p

In [101]:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html
lasso_cv_model = LassoCV(eps=0.001,n_alphas=1000,max_iter=10000)

In [102]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(max_iter=10000, n_alphas=1000)

In [103]:
lasso_cv_model.alpha_

0.00521862957399974

In [104]:
test_predictions = lasso_cv_model.predict(X_test)

In [105]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [106]:
MAE

0.37859918309711266

In [107]:
RMSE

0.769863505631881

In [108]:
# Training Set Performance
# Training Set Performance
train_predictions = lasso_cv_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.35311975421371405

In [109]:
lasso_cv_model.coef_

array([ 0.00000000e+00,  4.82665973e+00,  6.00855227e-01,  1.07189377e-01,
       -4.25041178e+00,  3.62309097e+00, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  1.12945575e+00, -0.00000000e+00,
       -1.30815297e-01,  1.65395257e-04,  4.92445257e-02,  7.62324705e-03,
        4.20071382e-02, -6.63279154e-02, -0.00000000e+00,  0.00000000e+00])

**Why this happenes?**

## Elastic Net

* combining the idea behind ridge regression and lasso to try to achieve the best of both worlds!

In [110]:
from sklearn.linear_model import ElasticNetCV

In [111]:
help(ElasticNetCV)

Help on class ElasticNetCV in module sklearn.linear_model._coordinate_descent:

class ElasticNetCV(sklearn.base.RegressorMixin, LinearModelCV)
 |  ElasticNetCV(*, l1_ratio=0.5, eps=0.001, n_alphas=100, alphas=None, fit_intercept=True, normalize=False, precompute='auto', max_iter=1000, tol=0.0001, cv=None, copy_X=True, verbose=0, n_jobs=None, positive=False, random_state=None, selection='cyclic')
 |  
 |  Elastic Net model with iterative fitting along a regularization path.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  Read more in the :ref:`User Guide <elastic_net>`.
 |  
 |  Parameters
 |  ----------
 |  l1_ratio : float or list of float, default=0.5
 |      float between 0 and 1 passed to ElasticNet (scaling between
 |      l1 and l2 penalties). For ``l1_ratio = 0``
 |      the penalty is an L2 penalty. For ``l1_ratio = 1`` it is an L1 penalty.
 |      For ``0 < l1_ratio < 1``, the penalty is a combination of L1 and L2
 |      This parameter can be a li

In [112]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],tol=0.01)

In [115]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],eps=0.001, max_iter=100000, n_alphas=100)

In [116]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

In [117]:
elastic_model.l1_ratio_

1.0

In [118]:
test_predictions = elastic_model.predict(X_test)

In [119]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [120]:
MAE

0.37859918309711266

In [121]:
RMSE

0.769863505631881

In [122]:
# Training Set Performance
# Training Set Performance
train_predictions = elastic_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.35311975421371405

In [123]:
elastic_model.coef_

array([ 0.00000000e+00,  4.82665973e+00,  6.00855227e-01,  1.07189377e-01,
       -4.25041178e+00,  3.62309097e+00, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  1.12945575e+00, -0.00000000e+00,
       -1.30815297e-01,  1.65395257e-04,  4.92445257e-02,  7.62324705e-03,
        4.20071382e-02, -6.63279154e-02, -0.00000000e+00,  0.00000000e+00])

# Feature engineering (especially data cleaning)

* The need for data cleaning
* The need for using domain knowledge
* Three main approaches:
    * extracting information (e.g. from timestamps)
    * combining information (e.g. using interaction between features)
    * transforming information (e.g. dealing with string data or categorical data, e.g. country)
        * integer encoding (be aware of interpreting as ordering)
        * dummy variables (i.e. category => 0 or 1, cons: creates many features, be aware of multicollinearity)